# Generated by Django 5.1.6 on 2025-02-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="JDResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=255)),
                ("weightage", models.IntegerField()),
                ("hr_comment", models.TextField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True, null=True)),
                (
                    "jd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="resume.jobdescription",
                    ),
                ),
            ],
        ),
    ]
