# Generated by Django 5.1.6 on 2025-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume_rename_weightage_jdresult_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="job_descriptions/"
            ),
        ),
    ]
