# Generated by Django 5.1.6 on 2025-03-02 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_jobdescription_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
