# Generated by Django 5.1.6 on 2025-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_alter_resume_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumedetails",
            name="candidate_application",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
