# Generated by Django 5.1.6 on 2025-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_alter_resume_id_alter_resumedetails_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumedetails",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
