# Generated by Django 5.1.6 on 2025-03-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0011_alter_resume_id_alter_resumedetails_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="compenstation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
