# Generated by Django 5.1.6 on 2025-03-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0012_jobdescription_compenstation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdescription",
            old_name="compenstation",
            new_name="compensation",
        ),
        migrations.AlterField(
            model_name="jdresult",
            name="jd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="resume.jobdescription",
            ),
        ),
    ]
