# Generated by Django 5.1.6 on 2025-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0013_rename_compenstation_jobdescription_compensation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedetails",
            name="flagged",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
