# Generated by Django 5.1.6 on 2025-03-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0014_resumedetails_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedetails",
            name="jd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jd_resumes",
                to="resume.jobdescription",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resumedetails",
            unique_together={("resume", "jd")},
        ),
    ]
