# Generated by Django 5.1.6 on 2025-03-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0015_resumedetails_jd_alter_resumedetails_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumedetails",
            name="jd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jd_resumes",
                to="resume.jobdescription",
            ),
        ),
    ]
