# Generated by Django 5.1.6 on 2025-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0017_resumedetails_score_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedetails",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
