# Generated by Django 5.1.6 on 2025-03-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0018_resumedetails_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumedetails",
            name="linkedin_url",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
