# Generated by Django 5.1.6 on 2025-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0021_alter_resumedetails_linkedin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="jdresult",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
    ]
