# Generated by Django 5.1.6 on 2025-03-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0022_jdresult_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="JDResultChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_by", models.CharField(max_length=255)),
                ("previous_score", models.IntegerField(blank=True, null=True)),
                ("updated_score", models.IntegerField(blank=True, null=True)),
                ("previous_hr_comment", models.TextField(blank=True, null=True)),
                ("updated_hr_comment", models.TextField(blank=True, null=True)),
                ("previous_rationale", models.TextField(blank=True, null=True)),
                ("updated_rationale", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="resume.jdresult",
                    ),
                ),
            ],
        ),
    ]
