# Generated by Django 5.1.6 on 2025-03-14 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0023_jdresultchangelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jdresultchangelog",
            name="changed_by",
        ),
    ]
