# Generated by Django 5.1.6 on 2025-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0024_remove_jdresultchangelog_changed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="jdresultchangelog",
            name="changed_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
