# Generated by Django 5.1.6 on 2025-03-14 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0025_jdresultchangelog_changed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jdresultchangelog",
            name="changed_by",
        ),
    ]
